# Get all sorts

GET http://localhost:3449/sorts

# Get all observations

GET http://localhost:3449/observations

# Get observation by sort

GET http://localhost:3449/observations/277076930200554

# Get observation by sort within a location

GET http://localhost:3449/observations/277076930200554/59.979978/10.721474/59.969842/10.735079

# Add a new observation

POST http://localhost:3449/observations
{
  :observation/sort 277076930200556
}
